version: '3.8'

services:
  app:
    container_name: questions-service
    image: questions-service:latest
    environment:
      DOCKER_DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db/${POSTGRES_DB}
    ports:
      - "8000:5000"
    depends_on:
      - postgres-db
    networks:
      - backend
    restart: unless-stopped
  
  db:
    container_name: postgres-db
    image: postgres
    env_file: 
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:${PGDATA}
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  db-data: