version: '3.8'

services:
  app:
    container_name: flask-app
  
  db:
    container_name: postgres-db
    image: postgres
    env_file: 
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:${PGDATA}
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  db-data: